### ISSUE TITLE
Annotate essential splice site mutations

### ISSUE THREAD

**Issue by hammer** [hammerlab/varcode#1]
@tmfromer mentioned that [PLINK/SEQ will do this annotation](https://bitbucket.org/statgen/plinkseq/src/master/sources/plinkseq/sources/lib/annot.cpp?at=master#cl-846).

**Comment by iskandr** [comment]
Thanks for this link, I'll try to keep the mutation annotations and their relative priorities similar to PLINK/SEQ.

**Comment by iskandr** [comment]
Useful reference: [Intronic and Exonic Nucleotide Variations that Affect RNA Splicing in Humans](https://www.iconceptpress.com/download/paper/12051922401407.pdf)

>The consensus sequence of the 5’ splice site is “CAG/GUAAGUAU”, where “/” indicates an exon-intron boundary

>The 3’ splice site consists of 3’ end of an intron and 5’ end of an exon, having a consensus sequence of “NYAG/R” (N, any nucleotide; Y, pyrimidine; R, purine; “/”, intron-exon boundary)

>It has been predicted that 16-20% of missense mutations disrupts ESEs and change the splicing pattern of the gene (Gorlov et al., 2003). Comparison of effects of mutations in HGMD and neutral SNPs in dbSNP on ESE/ESS hexamers and subsequent validation of an example of de novo generated ESSs revealed that 7,154 out of 27,681 missense and nonsense mutations (26%) are likely to cause exon skipping (Sterne- Weiler et al., 2011).

**Comment by iskandr** [comment]
Still missing: splice site mutations on the exon side.
