### ISSUE TITLE
UnboundLocalError in in_frame_coding_effect.py

### ISSUE THREAD

**Issue by leekaiinthesky** [hammerlab/varcode#107]
@iskandr Looks like it was meant to be `original_protein_subsequence`?

    ---------------------------------------------------------------------------
    UnboundLocalError                         Traceback (most recent call last)
    <ipython-input-3-2a9f0a5a4c80> in <module>()
          5         varcode_dict[v] = v.effects()
          6     return varcode_dict
    ----> 7 varcode_dict = _load_varcode_dict()

    <ipython-input-3-2a9f0a5a4c80> in _load_varcode_dict()
          3     variants = varcode.load_vcf('/Users/kai/Documents/hammerlab/temp.vcf', reference_name='hg19')
          4     for v in variants:
    ----> 5         varcode_dict[v] = v.effects()
          6     return varcode_dict
          7 varcode_dict = _load_varcode_dict()

    /Users/kai/src/varcode/varcode/common.pyc in wrapped_fn(*args, **kwargs)
         45             return memoized_values[key]
         46         except KeyError:
    ---> 47             memoized_values[key] = fn(*args, **kwargs)
         48             return memoized_values[key]
         49 

    /Users/kai/src/varcode/varcode/variant.pyc in effects(self, raise_on_error)
        391                 for transcript in transcripts_grouped_by_gene[gene_id]:
        392                     try:
    --> 393                         effect = self.effect_on_transcript(transcript)
        394                         effects.append(effect)
        395                     except (AssertionError, ValueError) as error:

    /Users/kai/src/varcode/varcode/common.pyc in wrapped_fn(*args, **kwargs)
         45             return memoized_values[key]
         46         except KeyError:
    ---> 47             memoized_values[key] = fn(*args, **kwargs)
         48             return memoized_values[key]
         49 

    /Users/kai/src/varcode/varcode/variant.pyc in effect_on_transcript(self, transcript)
        491 
        492         exonic_effect_annotation = self._exonic_transcript_effect(
    --> 493             exon, exon_number, transcript)
        494 
        495         # simple case: both start and end are in the same

    /Users/kai/src/varcode/varcode/variant.pyc in _exonic_transcript_effect(self, exon, exon_number, transcript)
        651             transcript_offset=transcript_offset,
        652             variant=self,
    --> 653             transcript=transcript)
        654 
        655         if changes_exonic_splice_site(

    /Users/kai/src/varcode/varcode/coding_effect.pyc in coding_effect(ref, alt, transcript_offset, variant, transcript)
        117             sequence_from_start_codon=sequence_from_start_codon,
        118             variant=variant,
    --> 119             transcript=transcript)
        120     else:
        121         return frameshift_coding_effect(

    /Users/kai/src/varcode/varcode/in_frame_coding_effect.py in in_frame_coding_effect(ref, alt, cds_offset, sequence_from_start_codon, transcript, variant)
        285         mutant_protein_subsequence = \
        286             mutant_protein_subsequence[n_shared_amino_acids:]
    --> 287         if mutation_aa_pos < len(original_protein_sequence) - 1:
        288             # only call this mutation a premature stop if it decreases
        289             # the length of the protein

    UnboundLocalError: local variable 'original_protein_sequence' referenced before assignment

**Comment by iskandr** [comment]
@leekaiinthesky What was the variant here?

**Comment by leekaiinthesky** [comment]
7 117120188 . A G . . . GT 0/1

**Comment by leekaiinthesky** [comment]
Not the one I just sent. Rather, this one:

7	117120188	.	A	AAGT	.	.	.	GT	0/1
