### ISSUE TITLE
move read_evidence module and Locus class to varlens

### ISSUE THREAD

**Issue by timodonnell** [hammerlab/varcode#124]
varcode is cleaner if the functionality for reading BAM files is in another library, and I think the library I'm developing called `varlens` is a reasonable place for that (https://github.com/timodonnell/varlens -- soon to be in hammerlab once it's cleaned up a bit). It will also hopefully lead to a less convoluted implementation of `read_evidence`.

This will also mitigate the absurd situation where varcode uses 1-based inclusive coordinates but `varcode.read_evidence` uses interbase coordinates.

**Comment by iskandr** [comment]
:+1:

**Comment by iskandr** [comment]
If you end up needing to parse Cufflinks tracking files, you can use https://github.com/hammerlab/topiary/blob/master/topiary/rna/cufflinks.py and if you need to parse GTFs (e.g. to pull out novel gene annotations) there is now https://github.com/hammerlab/gtfparse/tree/master/gtfparse
