### ISSUE TITLE
original_start doesn't get pickled

### ISSUE THREAD

**Issue by tavinathanson** [hammerlab/varcode#141]
Pickling is based on `getstate` and `setstate`, which don't include `original_ref`, `oirignal_alt` and `original_start`. This breaks `isovar` when running it on pickled variants.

@iskandr I'm just going to add those fields to `variant.fields()` unless you have a different idea?

**Comment by tavinathanson** [comment]
On second thought, that doesn't seem right. We should probably *only* pickle the original values, and then reconstruct the normalized values when loading.

**Comment by iskandr** [comment]
I think this is fixed with the new `Serializable`-based pickling logic.
