### ISSUE TITLE
replace `load_vcf` with `load_vcf_fast` ?

### ISSUE THREAD

**Issue by timodonnell** [hammerlab/varcode#144]
I'm trying to hack varcode to load the per-sample attributes (for guacamole benchmarking). I have `load_vcf_fast` doing what I need but getting `load_vcf` to return the same values is proving a little difficult. Maybe we should stop maintaining two implementations of vcf loading? Has anyone hit anything with `load_vcf_fast` that's made them downgrade to `load_vcf`?

**Comment by iskandr** [comment]
We could start by switching the two implementations and adding tests for
their equivalence.

**Comment by timodonnell** [comment]
Yeah, switching them first seems reasonable. We actually already have tests
for their equivalence here (these are the tests that are failing for me
after getting per-sample info to load):

https://github.com/hammerlab/varcode/blob/master/test/test_vcf.py#L73

**Comment by iskandr** [comment]
Switch happened, closing the issue.
