### ISSUE TITLE
Variant pickling won't work for not-human and non-EnsemblRelease Genomes

### ISSUE THREAD

**Issue by tavinathanson** [hammerlab/varcode#147]
See https://github.com/hammerlab/varcode/pull/146#discussion_r60986004

**Comment by iskandr** [comment]
Plan to fix this: instead of popping the release number, instead get the genome name and then call `genome_for_reference_name`

**Comment by iskandr** [comment]
Fixed by my elaborate conversion to Serializable and sercol.
