### ISSUE TITLE
load_vcf_fast fails when sample names contain spaces

### ISSUE THREAD

**Issue by iskandr** [hammerlab/varcode#158]
I was looking at a VCF where the sample name was "medullary thyroid" and got the following error from `load_vcf_fast`: 

```
CParserError: Too many columns specified: expected 11 and found 10
```

Using just `load_vcf` worked.

**Comment by iskandr** [comment]
@timodonnell Did you ever get around to fixing this? If not I can take a look at it.

**Comment by timodonnell** [comment]
Sorry, I started working on this then got side tracked. I think #160 should fix it.
