### ISSUE TITLE
Premature stop codon error

### ISSUE THREAD

**Issue by arahuja** [hammerlab/varcode#166]
Just saw this, posting for now, but will come back to investigate

Was with Ensembl 83

```
Premature stop codon cannot be at position 507 since the original protein of Transcript(id=ENST00000380476, name=EPHX2-002, gene_id=ENSG00000120915, gene_name=EPHX2, biotype=protein_coding, location=8:27491166-27544913) has length 502
```

**Comment by iskandr** [comment]
What variant was this from?

**Comment by arahuja** [comment]
Yea, investigating that, suprisingly hard to track down without instrumenting into the _varcode_ or getting the effects manually per variant.

**Comment by iskandr** [comment]
@arahuja Did you figure it out?

**Comment by iskandr** [comment]
I'm curious if https://github.com/hammerlab/varcode/pull/173 fixes this error.

**Comment by iskandr** [comment]
@arahuja Should I close this issue?

**Comment by arahuja** [comment]
Sure, I haven't had time to dig back into and have just ignoring the variant.
