### ISSUE TITLE
Wrong aa_mutation_end_offset for insertion of stop codon

### ISSUE THREAD

**Issue by iskandr** [hammerlab/varcode#175]
Submitted by João Eiras via email:

```
# PrematureStop Insertion
chr1 99772782 . A ACCCTGA 5000 .
# Annotated as
PrematureStop (OK)
* aa_mutation_start_offset  = 6 (OK)
* aa_mutation_end_offset = 7 (FAIL, should be 6)
* aa_ref = "L" (FAIL, just insertion, ref should be empty)
* aa_alt = "P"
```

**Comment by iskandr** [comment]
@joaoe 

After some thought I decided I disagree with the bug report's interpretation of `aa_mutation_end_offset`. I think that these offsets should indicate the offsets of mutated amino acids in the mutated protein sequence.

Thus `aa_mutation_end_offset=7` is fine (but `aa_ref='L'` is still wrong).

**Comment by joaoe** [comment]
Oh, my bad. Indeed it is 7 there.

**Comment by iskandr** [comment]
Fixed by https://github.com/hammerlab/varcode/pull/173
