### ISSUE TITLE
SNV results in deletion

### ISSUE THREAD

**Issue by arahuja** [hammerlab/varcode#193]
@iskandr I can't figure why this would happen

```Variant(contig='19', start=44417544, ref='G', alt='A', reference_name='GRCh37')```

has effects 

```
<EffectCollection with 3 elements>
  -- Deletion(variant=chr19 g.44417544G>A, transcript_name=ZNF45-001, transcript_id=ENST00000269973, effect_description=p.R681del)
  -- Deletion(variant=chr19 g.44417544G>A, transcript_name=ZNF45-002, transcript_id=ENST00000589703, effect_description=p.R681del)
  -- NoncodingTranscript(variant=chr19 g.44417544G>A, transcript_name=RP11-15A1.2-001, transcript_id=ENST00000586247)
```

This a single base change, shouldn't end up as a deletion then?  Somehow `trim_shared_flanking_strings` is returning a 0-length alternate amino acid?

**Comment by arahuja** [comment]
Investigating more, this G>A mutation is a CGA>TGA mutation, so it should R>* mutation, or `PrematureStop`.

The current condition in the code for a `PrematureStop` is 
```
    if mutant_codons_contain_stop and (
            n_aa_alt < n_ref_amino_acids_after_mutated_site):
```

The first condition `mutant_codons_contain_stop` is true, but the second is not, because `n_aa_alt == 0` and `n_ref_amino_acids_after_mutated_site == 0`

Is the fix just making this `<=`, I don't know enough about the edge cases here.

**Comment by iskandr** [comment]
This only affect PrematureStop effects at the last amino acid, so hopefully is pretty rare. Will fix in a second.
