### ISSUE TITLE
Use SPANR to identify splicing misregulation

### ISSUE THREAD

**Issue by hammer** [hammerlab/varcode#2]
* [Paper](http://www.sciencemag.org/content/early/2014/12/17/science.1254806.abstract)
* [Web service](http://tools.genes.toronto.edu)

**Comment by iskandr** [comment]
Like https://github.com/hammerlab/varcode/issues/46, I think this issue might be out of scope for Varcode. The library probably shouldn't step far beyond predicting deterministic(-ish) changes to the protein sequence. Opinions on closing?

**Comment by hammer** [comment]
Totally reasonable
