### ISSUE TITLE
Varcode noncoding variant in a drop_silent_and_noncoding() list

### ISSUE THREAD

**Issue by ihodes** [hammerlab/varcode#200]
![](http://link.isaachodes.io/300W3n1E0m3V/Screen%20Shot%202016-10-25%20at%206.13.08%20PM.png)

**Comment by iskandr** [comment]
What's the actual variant?

Also, the exon track on the bottom only shows you one transcript, are you sure that this variant doesn't have a coding effect on some other transcript?

**Comment by ihodes** [comment]
> Also, the exon track on the bottom only shows you one transcript, are you sure that this variant doesn't have a coding effect on some other transcript?

Aha, not at all.
