### ISSUE TITLE
Make Varcode correctly infer genome for b37-decoy string

### ISSUE THREAD

**Issue by julia326** [hammerlab/varcode#207]
Example string:

##reference=file:///demeter/scratch/username/ksinai-demeter/b37decoy-reference-genome/hs37d5.fasta

**Comment by iskandr** [comment]
@jburos I think that we talked about adding `startswith` cases to https://github.com/hammerlab/varcode/pull/182 at some point-- do you think it would be hard?

**Comment by jburos** [comment]
Not at all - would be pretty easy. Happy to take a look early next week

**Comment by julia326** [comment]
My bad, Varcode handles those strings just fine - this was an instance of an error message "Unable to infer genome etc." after a bad file download so it was a mess of HTML instead of a VCF.
