### ISSUE TITLE
Allow contig to be empty to allow parsing of MAF with faulty mutation(s)

### ISSUE THREAD

**Issue by tuomastik** [hammerlab/varcode#210]
I'm proposing `varcode.variant.Variant()` to allow (with warning message) an empty value in `contig` attribute instead of raising an exception. This way user will be able to use `load_maf` parser with faulty MAF where a mutation has an empty value in "Chromosome" field.

Current functionality:
```
>>> variant_collection = varcode.load_maf('missing_chr.maf')
TypeError: Chromosome cannot be 'nan' : <class 'float'>
```

Proposed functionality:
```
>>> variant_collection = varcode.load_maf('missing_chr.maf')
Warning: Something went wrong when normalizing chromosome: Chromosome cannot be 'nan' : <class 'float'>
```

**Comment by iskandr** [comment]
Huh, what's the use of a variant which lacks a chromosome? Wouldn't you rather catch the exception in `load_maf` and just skip that variant?

**Comment by tuomastik** [comment]
I'm using the MAF parser in a project where MAF files are provided by user. Thanks for the great work by the way. 👍 However, I recently ran into a user supplied MAF which contained thousands of perfectly formatted variants except for one that had a missing value in "Chromosome" field. Because of that one erroneous variant the whole parsing failed which I would now like to avoid by allowing (not skipping) variants lacking a chromosome and manually checking for missing chromosomes after the parsing is done.

**Comment by joaoe** [comment]
The `Variant.effects` method already accepts a `raise_on_error` parameter. You could use the same principle for load_vcf and load_maf. Something like:
```
# raise - raise exception when parsing broken variant
# keep broken variant object
# skip broken variant and do not create Variant object.
load_maf(..., on_error = ('raise', 'keep', 'skip'))
```

**Comment by iskandr** [comment]
@tuomastik Would you want to skip the variants with missing chromosomes or use external knowledge to fill them in? I'd like to fix your problem without allowing the construction of malformed `Variant` objects. 

Also, sorry for the slow response~ (cycling between different projects I guess leads to long lag times)

**Comment by tuomastik** [comment]
@iskandr I would not like to skip variants with missing chromosomes. I would be happy with malformed `Variant` objects because I'm passing the Varcode parsed variants through a custom validator. I understand that allowing malformed `Variant` objects is not something that you would like to allow, but actually @joaoe's suggestion sounds like a good middle ground solution to me, letting users to optionally allow malformed `Variant` objects.
