### ISSUE TITLE
Optionally allow duplicated mutations when using load_vcf or load_maf

### ISSUE THREAD

**Issue by tuomastik** [hammerlab/varcode#211]
Let's give user an option to allow duplicated variants when loading variants from a VCF or MAF by adding `distinct` parameter of `VariantCollection` to `load_vcf` and `load_maf`.

**Comment by iskandr** [comment]
That seems like a good idea, are you working on a PR for that?

**Comment by tuomastik** [comment]
Great! There is now a pull request. This PR will not change the default behavior of  `load_vcf` and `load_maf` because the same default value (`True`) is assigned to `distinct` parameter in `load_vcf` and `load_maf` declaration as in the declaration of `VariantCollection`.
