### ISSUE TITLE
Effect prediction throws error (even if raise_on_error=False)

### ISSUE THREAD

**Issue by johannesreiter** [hammerlab/varcode#213]
Executing the following code results in a ```sqlite3.OperationalError: no such column: exon_id``` independet if ```raise_on_error=False``` or ```raise_on_error=True```. Maybe this effect prediction is not possible based on hg18?
```
from varcode import Variant
from pyensembl import ensembl_grch36
# common driver gene mutation in KRAS
var = Variant(contig=12, start=25289551, ref="C", alt="A", ensembl=ensembl_grch36)
var.effects(raise_on_error=False)
```

**Comment by iskandr** [comment]
Hi @johannesreiter, the older Ensembl GTFs don't have exon IDs in them and Varcode relies on that field. Any of the GTFs for GRCh37 or GRCh38 won't have this problem, would it be possible for you to switch to a more recent reference? If not, I can try to fix this.

**Comment by johannesreiter** [comment]
I guessed that this is the problem. Since hg18 is so rare, it doesn't really matter. I was simply wondering if the error handling should be different as one would expect that no exception is raised when ```raise_on_error=False```.
With GRCh37 the prediction works extremely well. I like it a lot! Thanks!
