### ISSUE TITLE
Exception when deletion extends beyond exon boundary

### ISSUE THREAD

**Issue by iskandr** [hammerlab/varcode#224]
```ValueError: Wrong reference sequence for variant Variant(contig='11', start=106262686, ref='GTGAAGG', alt='', reference_name='GRCm38') on transcript Transcript(transcript_id=ENSMUST00000021049, name=Psmc5-001, gene_id=ENSMUSG00000020708, gene_name=Psmc5, biotype=protein_coding, location=11:106256154-106263120)
```

The end of exon 9 is “GTGAAG” and the next intronic nt is “G”. So the variant deletes the end of the exon and the next nucleotide. Varcode only looks at the transcript sequence and apparently doesn’t clip the variant to only cover the exons. (This seems like it would likely cause a splice variant, since both the exonic and intronic splice signal is potentially damaged).

**Comment by ihodes** [comment]
What is the right thing to do here?

**Comment by julia326** [comment]
Example where this comes up:
ValueError: Wrong reference sequence for variant Variant(contig='11', start=106262686, ref='GTGAAGG', alt='', reference_name='GRCm38') on transcript Transcript(transcript_id=ENSMUST00000021049, name=Psmc5-001, gene_id=ENSMUSG00000020708, gene_name=Psmc5, biotype=protein_coding, location=11:106256154-106263120)

**Comment by julia326** [comment]
Went over this with @iskandr. Varcode is doing the right thing and, when predicting the effect, trimming the variant to just the exon, but it's not altering the variant object itself - and isovar replicated the "does the reference match" check but didn't account for a variant reading into the intron. Solution: 1) remove that isovar check, 2) add a logging statement to varcode if it trims the variant like that and make sure it gets logged. Doing that shortly...

**Comment by julia326** [comment]
Issue moved to [hammerlab/isovar #82](https://github.com/hammerlab/isovar/issues/82) via [**ZenHub**](https://www.zenhub.com/)
