### ISSUE TITLE
support determining the evidence for a variant in a bam

### ISSUE THREAD

**Issue by timodonnell** [hammerlab/varcode#26]
This is basically what I'm working on now, but I thought I'd file a ticket since I'm not sure whether people will think it belongs in varcode.

I need functionality for taking a varcode `Variant` and a BAM (e.g. a pysam alignment object), and giving me some summary of what reads support / don't support that variant in the BAM. Note that my BAM might be a different BAM than what the original variant caller was run on.

Currently I'm imagining a varcode module called something like `VariantEvidence` that has a routine for taking a `Variant` and a pysam alignment object and gives me back some info (yet to be determined exactly what). I'd be fine to put this in a different project though if people have other suggestions.

**Comment by iskandr** [comment]
I need this also, to quantify allele specific expression in RNA-Seq BAMs. I
need to think a little more about whether this fits into Varcode, let's
talk about it in person tomorrow.

**Comment by iskandr** [comment]
Subsumed by varlens.
