### ISSUE TITLE
support filtering a variant collection to variants overlapping specified gene names

### ISSUE THREAD

**Issue by timodonnell** [hammerlab/varcode#32]
Currently I have to call variant.gene_names() for every variant, which is slow (I have ~80k variants).

A better implementation would be to use `pyensembl` to lookup the intervals for the genes I'm interested, then filter the variants by position quickly. It would be useful if that functionality were part of `VariantCollection`.

**Comment by iskandr** [comment]
@timodonnell Do you think we still need this?

**Comment by timodonnell** [comment]
I have no current need for this, feel free to close
