### ISSUE TITLE
Predict coding sequence of StartLoss mutations

### ISSUE THREAD

**Issue by iskandr** [hammerlab/varcode#4]
If we get the intron sequence, we can look for an alternative Kozak consensus sequence (http://en.wikipedia.org/wiki/Kozak_consensus_sequence). Since this pattern is inexact we probably need to use a probabilistic model and look for the closest high scoring start codon.

**Comment by JPFinnigan** [comment]
Jim Manfredi lectured on this topic for the PhD course. If you have any questions about the biology he might be able to help.

**Comment by iskandr** [comment]
There are bigger fish to fry at the moment but I'd love to come back to this once the bigger features of varcode & immuno have stabilized. This could also become higher priority if we encounter a patient who has one of these mutations.

**Comment by iskandr** [comment]
Probably never going to give a single answer to the protein sequence of start loss variants.
