### ISSUE TITLE
VariantCollection.high_priority_effect != Variant.top_effect

### ISSUE THREAD

**Issue by tavinathanson** [hammerlab/varcode#58]
I'd expect `Variant` to also have a `high_priority_effect`: the same as `top_effect`, with a min filter.

**Comment by iskandr** [comment]
@arahuja @timodonnell @tavinathanson 

I'm currently reorganizing `Varcode` so `VariantCollection.effects()` returns an `EffectCollection` which has a small `top_effect_per_variant()` that's defined as
```
return {
   variant: top_priority_effect(variant_effects)
   for (variant, variant_effects) in
   self.groupby_variant().items()
```

If you only want to see effects that affect splicing or the protein sequence, you can make a smaller effect collection by calling:

`ec.filter_silent().top_effect_per_variant()`. 

Does this seem reasonable to you guys?

**Comment by tavinathanson** [comment]
What is each member of an `EffectCollection`? A `MutationEffect`?

Does Variant.effects() also return an `EffectCollection`?

**Comment by iskandr** [comment]
Yes and yes.

**Comment by iskandr** [comment]
Yes and yes.

**Comment by tavinathanson** [comment]
Makes sense to me! I don't remember what the previous concerns were (and I think there were concerns?) about having a separate `EffectCollection` class.

**Comment by iskandr** [comment]
@tavinathanson I think it wasn't clear that we needed it, so it was adding boilerplate around things we could do more simply with simple lists and dicts. I think now that the API is emerging from the murkiness of imagination, it actually seems useful to between `VariantCollection` and `EffectCollection`.

**Comment by iskandr** [comment]
Fixed by https://github.com/hammerlab/varcode/pull/66
