### ISSUE TITLE
KeyError: 'reference' in load_vcf

### ISSUE THREAD

**Issue by arahuja** [hammerlab/varcode#60]
`varcode.vcf.load_vcf` gives an error:

```
     61     if not ensembl_release:
     62         reference_path = vcf_reader.metadata[reference_path_field]
---> 63         reference_name = infer_reference_name(reference_path)
     64         ensembl_release = ensembl_release_number_for_reference_name(
     65                 reference_name)

KeyError: 'reference'
```

This occurs when `ensembl_release` is not specified and the VCF does not list the reference.  Maybe its easier to require the reference or ensembl release? 

If not, this can be wrapped in a more informative error as well

Let me know if you are interested in me adding either change.

**Comment by iskandr** [comment]
Want to add a friendlier error message?

**Comment by arahuja** [comment]
Sure, I'll do that

**Comment by timodonnell** [comment]
+1 just hit this
