### ISSUE TITLE
investigate porting read evidence module to use impala

### ISSUE THREAD

**Issue by timodonnell** [hammerlab/varcode#69]
CC'ing @ihodes and @ryan-williams 

My `pysam`-based `varcode.read_evidence` module seems to cap out at making pileups for about 100 loci / second. This is true for both NFS access and local disk access. My current guess is that pysam is rate limited by stepping through all the reads that don't match my locus of interest, but do fall within the same index bucket as my locus. If that's true, then this is essentially the speed limit for random access into BAM files.

I would be very interested to see if it's possible to get impala to generate pileups much faster than 100 pileups / sec. If it is, it would be great to port my `read_evidence` module to support an impala backend.

**Comment by ihodes** [comment]
I'm on it! I need to load the reference genome into Impala; generating pileups will be easy from there.

**Comment by timodonnell** [comment]
Cool!

Note: for the purposes of `read_evidence`, we shouldn't need the reference sequence. The API is just to give a summary of the bases read at a given set of loci in a BAM. The caller can compare the results to the reference as needed.

**Comment by ihodes** [comment]
Ah yeah—we need the reference to generate the pileups, using it as one side of a join, as we can't really go from `n → m, m > n` rows in Impala any other way, AFAIK.

**Comment by hammer** [comment]
@ihodes can you sketch the schema and sql you have in mind to generate a pileup?

**Comment by ihodes** [comment]
Something like to generate the pileups (on `pileupname`), could group by or aggregate/concat seqs instead, whatever. This is the idea:

```
SELECT concat(ref.position, ref.contig) pileupname, bam.*
FROM bam, ref
WHERE
  ref.contig = bam.contig__contigname
  AND ref.`position` BETWEEN bam.`start` AND bam.`end`
;
```

Schema for BAM is like it is now, schema for ref is e.g. `contig string, position integer, base string`.

**Comment by iskandr** [comment]
Maybe worth reopening under [varlens](http://www.github.com/hammerlab/varlens).
