### ISSUE TITLE
Make Variants pickle-able

### ISSUE THREAD

**Issue by iskandr** [hammerlab/varcode#77]
Need an implementation of `__getstate__` and `__setstate__` to reduce `EnsemblRelease` objects to their version and then reconstruct that `EnsemblRelease` using `pyensembl.cached_release`. 

See: https://docs.python.org/2/library/pickle.html#pickle-protocol

**Comment by hammer** [comment]
I haven't been following this work but why are we using pickle as our serialization protocol?

**Comment by iskandr** [comment]
It's not the only one, I think the VCF serialization is more important. 

But pickling is ubiquitous in Python, so we should support that too. 

@timodonnell If you feel inspired while I'm gone: https://github.com/hammerlab/varcode/issues/18 (following ANN for effect annotations probably needs to be its own issue)

**Comment by hammer** [comment]
In general I strongly prefer cross-language serialization protocols to language-specific ones. Avro is particularly nice in Python as it doesn't require any codegen. I haven't really looked at the current use case but if the serialized data is expected to live longer than the program pickle is rarely a good idea.

**Comment by iskandr** [comment]
I don't have any objections to `to_avro()`, `to_json()`, or whatever. But
you'll need to write something `__getstate__` and `__setstate__` for those
anyway.

On Wed, Apr 29, 2015 at 3:52 PM, Jeff Hammerbacher <notifications@github.com
