### ISSUE TITLE
compare variants that use different references

### ISSUE THREAD

**Issue by timodonnell** [hammerlab/varcode#83]
Not sure if this is really possible. It would great to be able to compare a variant (or locus perhaps) aligned against hg18 with one aligned with grch37 and have the result be True if the variants are in logically the same place in the genome.

Just hit an issue now where I'm realizing the TCGA MAF files use all sorts of different references so considering only genomic position for the variants in them results in a set of variants that appear different but are really referring to the same event. Having some way to work coherently with a set of variants aligned to different references would be really useful.

**Comment by iskandr** [comment]
There are some "liftover" scripts for migrating hg18 MAFs to hg19. However,
this is really a partial function which can fail for some (many?) variants.
If we added mappings between interval ranges of references to PyEnsembl we
could make a comparison function which sometimes works and sometimes
fails...is that useful?

**Comment by timodonnell** [comment]
Yeah, I think having a function that does this on a "best effort" kind of
way and fails if it can't be sure what it's doing is right is the way to
go. This would be useful for what I'm doing but I'm not sure how often it
will come up in the future, and it does seem like a substantial amount of
work to get right.

**Comment by iskandr** [comment]
@timodonnell What do you think of abandoning any plans of supporting "liftover" from older references? It seems like if you want to use a newer reference then you should just align to it from raw reads.

**Comment by timodonnell** [comment]
Yeah, I agree this should be out of scope for varcode
