### ISSUE TITLE
pip installing Varcode doesn't seem to work lately

### ISSUE THREAD

**Issue by tavinathanson** [hammerlab/varcode#84]
In my `site-packages`, I don't end up with `varcode` even though I do end up with `varcode-0.3.9.dist-info`. `pip list` thinks I have `varcode`, but `import varcode` fails.

**Comment by tavinathanson** [comment]
I reproduced this, and there appears to be nothing in `top_level.txt`

**Comment by tavinathanson** [comment]
(Re-uploading to PyPi didn't help)

**Comment by hammer** [comment]
I see this trying to install from varcode master too.
