### ISSUE TITLE
Travis should include setup.py testing

### ISSUE THREAD

**Issue by tavinathanson** [hammerlab/varcode#86]
When Travis is set up, we should be sure that it includes testing `setup.py` itself. (To avoid issues like #84.)

**Comment by iskandr** [comment]
Is this still relevant? If so, how do we test `setup.py` separate from installing with pip?

**Comment by tavinathanson** [comment]
Not totally clear what I meant; seems like Travis automatically tests `setup.py` via pip? Closing.
