### ISSUE TITLE
handle single-sample VCFs with INFO fields containing list values of size > 1

### ISSUE THREAD

**Issue by timodonnell** [hammerlab/varcode#9]
VariantCollection (in the flatten_info_dictionary function) assumes that all INFO fields are lists of size 1. However, GATK HaplotypeCaller, running on a single sample, appears to output VCFs that have INFO values with > 1 elements. For example, the "MLEAC" INFO element is per-allele, not per-sample: "Maximum likelihood expectation (MLE) for the allele counts (not necessarily the same as the AC), for each ALT allele, in the same order as listed".

Currently, when loading a HaplotypeCaller VCF, we get a assertion error in flatten_info_dictionary. Probably the fix is to not attempt to flatten the dictionary.

**Comment by iskandr** [comment]
Fixed by https://github.com/hammerlab/varcode/pull/11
