### ISSUE TITLE
Improve the README to include some examples of working with Varcode in IPython

### ISSUE THREAD

**Issue by hammer** [hammerlab/varcode#95]
@iskandr you recently got @armish and @nickscaglione up to speed on Varcode so perhaps you could work with them to get some of your code examples into the README?

**Comment by armish** [comment]
One thing that was really helpful for me was the iPython notebook from our walk-through session with @iskandr. I can help by creating a polished one and highlight a few basic concepts (such as importing variants from MAF/VCF, annotating and accessing them) in the notebook for people to kickstart with the library. 

Will that be helpful?

**Comment by iskandr** [comment]
@armish That would be great, let me know if you need help with anything. 

@hammer What do you think of https://github.com/hammerlab/varcode/tree/examples-in-README?
