### ISSUE TITLE
Is a VariantCollection single sample or multiple samples?

### ISSUE THREAD

**Issue by arahuja** [hammerlab/varcode#96]
If it's multiple samples - where's the best place to save the SampleId - right now unless I set `distinct=True` it would throw out repeated varaints?

**Comment by timodonnell** [comment]
In #94 I'm suggesting moving the non-essential variant info into a separate
dict that's part of VariantCollection to make cases like this easier to
deal with. Where are you getting the SampleId from though -- is it coming
in from the INFO field in a VCF?

**Comment by arahuja** [comment]
@timodonnell I'm not getting a sample ID (yet), but I was asking what the best place would be to save that information.

**Comment by timodonnell** [comment]
Gotcha. I'd advocate for keeping Variant instances very simple (only have
properties that affect variant equality, no extra metdata) and then having
separate dict(s) to map between those variants and their extended
properties like sample id. Interested what others think.

**Comment by iskandr** [comment]
There is something conceptually nice about having `Variant` be just its fundamental properties (chr, pos, ref, alt, genome) and moving metadata onto some container. It's not clear to me how that should be organized-- should a variant collection keep tabs on which samples had which variants? Do either of you have "ideal" example code of how metadata should be used within Varcode? What if we combined two variant call sets which have the same variant from the same sample but with differences in depth?

**Comment by iskandr** [comment]
After looking over @timodonnell's last PR I think that we should stick with `VariantCollection` being for a single sample, otherwise the metadata dictionary will get very confusing (since it will have to become a Variant -> sample -> metadata field mapping)

**Comment by iskandr** [comment]
...on the other hand this does `VariantCollection` the wrong object for loading a MAF file (which can have the same variant from multiple patients). 

@arahuja @timodonnell Any idea for what's best to do?

**Comment by arahuja** [comment]
@iskandr @timodonnell This seems close-able? The solution seems to be `VariantCollection` is a single sample, and then perhaps `load_maf` should load a dict of sample -> variant collection?

Saving the metadata somewhere would be useful though

**Comment by timodonnell** [comment]
That seems reasonable to me @arahuja . Then I guess we would need a `load_multisample_vcf` that returns a similar dict of sample -> variant collection. IIRC the metadata is currently stored in `VariantCollection.metadata`, or did you mean something else?

**Comment by arahuja** [comment]
>  IIRC the metadata is currently stored in VariantCollection.metadata, or did you mean something else?

Oh, didn't know that, I wasn't sure if we merged that in ever
