### ISSUE TITLE
Why does EffectCollection have top_priority_effect_per_variant but a variant doesn't have a top_priority effect

### ISSUE THREAD

**Issue by arahuja** [hammerlab/varcode#97]
I know there was a lot of back and forth on this, so I'm not sure if this just old code that should be removed.  If not, there doesn't seem to be an easy way to get to top effect per variant, but if I have an effect collection I can.

i.e.

I can do
```
ec = v.effects()
ec.top_priority_effect_per_variant()
```

but nothing directly to go from variant to top priority effect?

**Comment by iskandr** [comment]
To get the top priority effect for a variant, you need to construct the full effect collection behind the scenes anyway, so it seemed a little less magical to only put this method on the `EffectCollection` (making it obvious what's taking a while). However, we can easily add a helper like `Variant.top_effect`, would that be useful to you?

**Comment by arahuja** [comment]
I guess my other confusion on this was how many variants does an `EffectCollection` correspond to?  A `Variant` has an `EffectCollection` but then an `EffectCollection` has many variants?

**Comment by timodonnell** [comment]
I think having a `variant.top_effect` attribute like in older versions of varcode is a useful convenience (it also is fully table completeable in Ipython, whereas `variant.effects().top_priority_effect` is not)

**Comment by iskandr** [comment]
@timodonnell Do you still want `variant.top_priority_effect()`?

**Comment by timodonnell** [comment]
Forgot about this, but what we have now seems to be working for me. Fine by me to close
